### ISSUE TITLE
pip installation is broken

### ISSUE THREAD

**Issue by ror6ax** [opentracing-contrib/python-redis#3]
```
Collecting redis_opentracing
  Using cached https://files.pythonhosted.org/packages/e2/69/7519ff18c7444a96f5580e1594597ba53b8798e26b37aba5199970dff1c6/redis_opentracing-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-YpIjpG/redis-opentracing/setup.py", line 3, in <module>
        version = open('VERSION').read()
    IOError: [Errno 2] No such file or directory: 'VERSION'
```

Packaged file does not have VERSION file inside of it, hence the installation failure. Please re-release the artifact.

**Comment by carlosalberto** [comment]
Fixed already, had forgotten to close.
